/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Button' type
 */
export type ButtonTypeCodename = keyof Pick<Record<TypeCodenames, null>, "button">

/*
 * Typeguard for codename of 'Button' type
 */
export function isButtonTypeCodename(value: string | undefined | null): value is ButtonTypeCodename {
	return typeof value === "string" && value === ("button" satisfies ButtonTypeCodename)
}

/*
 * Button
 *
 * Id: abd2d033-2add-4a5d-aa3e-111627995cbc
 * Codename: button
 */
export type ButtonType = IContentItem<
	{
		/*
		 * href
		 *
		 * Codename: href
		 * Id: c278ead3-469c-462f-892c-3f8de3cd2dfe
		 * Type: text
		 * Required: true
		 */
		readonly href: Elements.TextElement

		/*
		 * variant
		 *
		 * Codename: variant
		 * Id: 5e7b4f52-dcc6-4225-bedc-efd029cf82e6
		 * Type: multiple_choice
		 * Required: true
		 */
		readonly variant: Elements.MultipleChoiceElement<ButtonTypeVariantMultipleChoiceOptions>
	},
	ButtonTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Button
 */
export type ButtonTypeElementCodenames = "href" | "variant"

/*
 * Type guard for Button
 *
 * Id: abd2d033-2add-4a5d-aa3e-111627995cbc
 * Codename: button
 */
export function isButtonType(item: IContentItem | undefined | null): item is ButtonType {
	return item?.system.type === ("button" satisfies ButtonTypeCodename)
}

export type ButtonTypeVariantMultipleChoiceOptions = "primary" | "secondary" | "tertiary" | "brand" | "text"
