/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { CoreType, TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"
import type { MenuType } from "../types/menu-type.generated.ts"

/*
 * Type representing codename of 'Homepage' type
 */
export type HomepageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "homepage">

/*
 * Typeguard for codename of 'Homepage' type
 */
export function isHomepageTypeCodename(value: string | undefined | null): value is HomepageTypeCodename {
	return typeof value === "string" && value === ("homepage" satisfies HomepageTypeCodename)
}

/*
 * Homepage
 *
 * Id: 443f59f5-bbdf-5580-a375-a2bc439b7734
 * Codename: homepage
 * External Id: 01a544c5-0b8d-4d3d-b9d9-79a6061be9b8
 */
export type HomepageType = IContentItem<
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: f2b93d3c-21c5-539b-9297-f3d55ae234eb
		 * External Id: 616122e8-9260-4272-abc5-5c9bdc261620
		 * Type: text
		 * Required: false
		 */
		readonly title: Elements.TextElement

		/*
		 * Subpages
		 *
		 * Codename: subpages
		 * Id: 2ed029bc-7d02-5775-a54a-a1469fa8d847
		 * External Id: 576128ed-80ad-4ffd-9302-c813ce898de0
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: menu
		 */
		readonly subpages: Elements.LinkedItemsElement<MenuType>

		/*
		 * Content
		 *
		 * Codename: content
		 * Id: bfd1de9c-afb9-53ab-ad76-6b4d6ef73e0a
		 * External Id: 89747012-1ecc-4363-8c4c-514b0a4cd081
		 * Type: modular_content
		 * Required: false
		 */
		readonly content: Elements.LinkedItemsElement<CoreType>
	},
	HomepageTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Homepage
 */
export type HomepageTypeElementCodenames = "title" | "subpages" | "content"

/*
 * Type guard for Homepage
 *
 * Id: 443f59f5-bbdf-5580-a375-a2bc439b7734
 * Codename: homepage
 * External Id: 01a544c5-0b8d-4d3d-b9d9-79a6061be9b8
 */
export function isHomepageType(item: IContentItem | undefined | null): item is HomepageType {
	return item?.system.type === ("homepage" satisfies HomepageTypeCodename)
}
