/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"
import type { PageType } from "../types/page-type.generated.ts"

/*
 * Type representing codename of 'Menu Item' type
 */
export type MenuItemTypeCodename = keyof Pick<Record<TypeCodenames, null>, "menu_item">

/*
 * Typeguard for codename of 'Menu Item' type
 */
export function isMenuItemTypeCodename(value: string | undefined | null): value is MenuItemTypeCodename {
	return typeof value === "string" && value === ("menu_item" satisfies MenuItemTypeCodename)
}

/*
 * Menu Item
 *
 * Id: 8be4c041-6021-58a2-8414-c32614ddda49
 * Codename: menu_item
 * External Id: b7522b37-e6d4-4c18-93e0-4695af1bfe32
 */
export type MenuItemType = IContentItem<
	{
		/*
		 * Label
		 *
		 * Codename: label
		 * Id: c71b2e03-533f-590a-b94f-f96a13e56977
		 * External Id: b32c3b40-b2c1-4548-844e-d536ee8af60b
		 * Type: text
		 * Required: false
		 */
		readonly label: Elements.TextElement

		/*
		 * Slug
		 *
		 * Codename: slug
		 * Id: 8402c119-8416-590f-a14a-08285d4b669b
		 * External Id: 7f056553-0b5b-4148-b9e7-f45997653b8e
		 * Type: url_slug
		 * Required: false
		 */
		readonly slug: Elements.UrlSlugElement

		/*
		 * Content
		 *
		 * Codename: content
		 * Id: 0c82039b-7738-5eda-8757-df6d3cbf5b4e
		 * External Id: 8617f619-10a2-47fb-bc4d-fa1597177109
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: page
		 */
		readonly content: Elements.LinkedItemsElement<PageType>
	},
	MenuItemTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Menu Item
 */
export type MenuItemTypeElementCodenames = "label" | "slug" | "content"

/*
 * Type guard for Menu Item
 *
 * Id: 8be4c041-6021-58a2-8414-c32614ddda49
 * Codename: menu_item
 * External Id: b7522b37-e6d4-4c18-93e0-4695af1bfe32
 */
export function isMenuItemType(item: IContentItem | undefined | null): item is MenuItemType {
	return item?.system.type === ("menu_item" satisfies MenuItemTypeCodename)
}
