/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Site Metadata' type
 */
export type SiteMetadataTypeCodename = keyof Pick<Record<TypeCodenames, null>, "site_metadata">

/*
 * Typeguard for codename of 'Site Metadata' type
 */
export function isSiteMetadataTypeCodename(value: string | undefined | null): value is SiteMetadataTypeCodename {
	return typeof value === "string" && value === ("site_metadata" satisfies SiteMetadataTypeCodename)
}

/*
 * Site Metadata
 *
 * Id: 06f7e41c-bef0-5013-9cd4-84fa72b95e32
 * Codename: site_metadata
 * External Id: 25c18404-5c71-4abd-85d0-0c3900bfff70
 */
export type SiteMetadataType = IContentItem<
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 0c828cd9-32b4-5278-a290-030595980f2c
		 * External Id: a798bab1-940c-47fa-b8f3-6713baa593b9
		 * Type: text
		 * Required: false
		 */
		readonly title: Elements.TextElement

		/*
		 * Subtitle
		 *
		 * Codename: subtitle
		 * Id: 898b3b51-4474-5bc2-9661-162001e73da6
		 * External Id: 6e8eccea-0d6b-4154-bf91-bb4d74dd03e5
		 * Type: text
		 * Required: false
		 */
		readonly subtitle: Elements.TextElement

		/*
		 * Copyright
		 *
		 * Codename: copyright
		 * Id: d04d0ce7-60ba-5c14-b00a-909797c6de51
		 * External Id: 74f849bf-cc31-4138-85fe-49b023394063
		 * Type: text
		 * Required: false
		 */
		readonly copyright: Elements.TextElement

		/*
		 * Domain
		 *
		 * Codename: domain
		 * Id: 59527f79-76d6-5da2-8271-5a5bef95c6a5
		 * External Id: 91e1b282-c6f9-426a-9855-5b811f7cdc54
		 * Type: text
		 * Required: true
		 */
		readonly domain: Elements.TextElement

		/*
		 * Page not found message
		 *
		 * Codename: page_not_found_message
		 * Id: b07825ef-c812-57a0-a608-735dc9a9ffe8
		 * External Id: ff4d4f1d-c0be-49cc-8cbe-ea2001e89a45
		 * Type: text
		 * Required: true
		 */
		readonly page_not_found_message: Elements.TextElement
	},
	SiteMetadataTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Site Metadata
 */
export type SiteMetadataTypeElementCodenames = "title" | "subtitle" | "copyright" | "domain" | "page_not_found_message"

/*
 * Type guard for Site Metadata
 *
 * Id: 06f7e41c-bef0-5013-9cd4-84fa72b95e32
 * Codename: site_metadata
 * External Id: 25c18404-5c71-4abd-85d0-0c3900bfff70
 */
export function isSiteMetadataType(item: IContentItem | undefined | null): item is SiteMetadataType {
	return item?.system.type === ("site_metadata" satisfies SiteMetadataTypeCodename)
}
