/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated.ts"
import type { LanguageCodenames } from "../system/languages.generated.ts"
import type { TypeCodenames } from "../system/types.generated.ts"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts"

/*
 * Type representing codename of 'Tag' type
 */
export type TagTypeCodename = keyof Pick<Record<TypeCodenames, null>, "tag">

/*
 * Typeguard for codename of 'Tag' type
 */
export function isTagTypeCodename(value: string | undefined | null): value is TagTypeCodename {
	return typeof value === "string" && value === ("tag" satisfies TagTypeCodename)
}

/*
 * Tag
 *
 * Id: 8c06a8ac-3a77-5743-8357-26c4ee5158be
 * Codename: tag
 * External Id: 92353f19-a4a1-45f0-8523-f7d71ee994d5
 */
export type TagType = IContentItem<
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: d0f41945-e215-5909-b01e-5cd98080d9b8
		 * External Id: dd2cf358-0359-4340-82fa-8352a2022efb
		 * Type: text
		 * Required: true
		 */
		readonly title: Elements.TextElement

		/*
		 * Slug
		 *
		 * Codename: slug
		 * Id: 0ca00763-cf16-573c-b3f2-cdf2aaad4b9e
		 * External Id: 70cdc258-c179-4f01-a814-330ab3e8a706
		 * Type: url_slug
		 * Required: true
		 */
		readonly slug: Elements.UrlSlugElement
	},
	TagTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Tag
 */
export type TagTypeElementCodenames = "title" | "slug"

/*
 * Type guard for Tag
 *
 * Id: 8c06a8ac-3a77-5743-8357-26c4ee5158be
 * Codename: tag
 * External Id: 92353f19-a4a1-45f0-8523-f7d71ee994d5
 */
export function isTagType(item: IContentItem | undefined | null): item is TagType {
	return item?.system.type === ("tag" satisfies TagTypeCodename)
}
