/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['menu_items', 'label', 'slug', 'content', 'title', 'subpages', 'subtitle', 'copyright', 'domain', 'page_not_found_message', 'name', 'bio', 'avatar_image', 'email', 'telegram', 'twitter', 'github', 'rss', 'vk', 'text', 'meta_description', 'description', 'gatsby_template', 'date', 'category', 'tags', 'url', 'show_in_navigation'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };