/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { MenuType } from '../types/menu-type.generated.js';
import type { MenuItemType } from '../types/menu-item-type.generated.js';
import type { HomepageType } from '../types/homepage-type.generated.js';
import type { SiteMetadataType } from '../types/site-metadata-type.generated.js';
import type { TagType } from '../types/tag-type.generated.js';
import type { AuthorType } from '../types/author-type.generated.js';
import type { CategoryType } from '../types/category-type.generated.js';
import type { NoteType } from '../types/note-type.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { ArticleType } from '../types/article-type.generated.js';
import type { WebSpotlightRootType } from '../types/web-spotlight-root-type.generated.js';
import type { PageType } from '../types/page-type.generated.js';

            /*
* Array of all type codenames
*/
            export const typeCodenames = ['menu', 'menu_item', 'homepage', 'site_metadata', 'tag', 'author', 'category', 'note', 'page', 'article', 'web_spotlight_root', 'page_52b1c1a'] as const;;
           
            /*
* Type representing all type codenames
*/
            export type TypeCodenames = typeof typeCodenames[number];;

            /*
* Typeguard for type codename
*/
            export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
                return typeof value === 'string' && (typeCodenames as readonly string[]).includes(value);
            };

					 /*
* Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
*/
					 export type CoreType = MenuType | MenuItemType | HomepageType | SiteMetadataType | TagType | AuthorType | CategoryType | NoteType | PageType | ArticleType | WebSpotlightRootType | PageType

					/*
* Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
*/
					export type CodenameTypeMapping = {
	readonly menu: MenuType,
readonly menu_item: MenuItemType,
readonly homepage: HomepageType,
readonly site_metadata: SiteMetadataType,
readonly tag: TagType,
readonly author: AuthorType,
readonly category: CategoryType,
readonly note: NoteType,
readonly page: PageType,
readonly article: ArticleType,
readonly web_spotlight_root: WebSpotlightRootType,
readonly page_52b1c1a: PageType,
};

					/*
* Helper type that returns type based on the codename of type.
*/
					export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping ? CodenameTypeMapping[TTypeCodename] : CoreType;
					