/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CategoryType } from '../types/category-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { TagType } from '../types/tag-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Article' type
*/
            export type ArticleTypeCodename = keyof Pick<Record<TypeCodenames, null>, "article">;

            /*
* Typeguard for codename of 'Article' type
*/
            export function isArticleTypeCodename(value: string | undefined | null): value is ArticleTypeCodename {
                return typeof value === 'string' && value === ('article' satisfies ArticleTypeCodename);
            }

/*
    * Article
    *
    * Id: 1f19c9de-51a2-55bd-96c5-dfab198a4e2d
* Codename: article
* External Id: e97ec6dc-1531-4b29-a84b-b17a85e79f05
    */
export type ArticleType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: c9303ea0-8bae-5899-a90f-5360cbb88051
* External Id: c851dd90-d897-4c31-b652-ad6f4b924f3f
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Description
    *
    * Codename: description
* Id: ae39552a-a464-5e99-ab2b-790e8d24a96c
* External Id: 6b780443-1d56-498a-b48c-25d0da41f1df
* Type: text
* Required: false
    */
                readonly description: Elements.TextElement;

/*
    * Content
    *
    * Codename: content
* Id: 7c792794-4746-5afb-8b82-5212ce4991a0
* External Id: a0bcb5d6-8aa0-45aa-8d7e-6c296ad93549
* Type: rich_text
* Required: true
    */
                readonly content: Elements.RichTextElement<CoreType>;

/*
    * Date
    *
    * Codename: date
* Id: 3beb2edb-b3bf-5ac9-8c7c-1d5ead2869ec
* External Id: 29d0c15f-9b3f-4211-be9d-18c8819bfe77
* Type: date_time
* Required: true
    */
                readonly date: Elements.DateTimeElement;

/*
    * Category
    *
    * Codename: category
* Id: 9e5d2aac-e9bc-5b24-a7f3-a2cefeb33283
* External Id: b8fc87c2-5f89-4b12-984e-3cdc4382f3e0
* Type: modular_content
* Required: true
* Allowed content types: category
    */
                readonly category: Elements.LinkedItemsElement<CategoryType>;

/*
    * Tags
    *
    * Codename: tags
* Id: 612e19d3-6d26-582c-947f-f8ff023b1f76
* External Id: 0e1a80dc-0768-458b-8039-dcdcad7fca16
* Type: modular_content
* Required: true
* Allowed content types: tag
    */
                readonly tags: Elements.LinkedItemsElement<TagType>;

/*
    * Slug
    *
    * Codename: slug
* Id: 3469a1e2-822d-5805-a93b-fca49b785092
* External Id: 0bc7d2a4-1d6a-4e47-93bb-0bf8a2422b0c
* Type: url_slug
* Required: false
    */
                readonly slug: Elements.UrlSlugElement;}, 
ArticleTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Article
*/
export type ArticleTypeElementCodenames = 'title' | 'description' | 'content' | 'date' | 'category' | 'tags' | 'slug';;

/*
    * Type guard for Article
    *
    * Id: 1f19c9de-51a2-55bd-96c5-dfab198a4e2d
* Codename: article
* External Id: e97ec6dc-1531-4b29-a84b-b17a85e79f05
    */
export function isArticleType(item: IContentItem | undefined | null): item is ArticleType {
                return item?.system.type === ('article' satisfies ArticleTypeCodename);
            };



            