/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Author' type
*/
            export type AuthorTypeCodename = keyof Pick<Record<TypeCodenames, null>, "author">;

            /*
* Typeguard for codename of 'Author' type
*/
            export function isAuthorTypeCodename(value: string | undefined | null): value is AuthorTypeCodename {
                return typeof value === 'string' && value === ('author' satisfies AuthorTypeCodename);
            }

/*
    * Author
    *
    * Id: ef0e5861-907e-5592-b4b4-cb8574a4e887
* Codename: author
* External Id: 337a4509-0793-4dda-ba6a-a071ff7e65f1
    */
export type AuthorType = IContentItem<
{
/*
    * Name
    *
    * Codename: name
* Id: 6436b43d-08b8-551a-b19c-9663dcd7787f
* External Id: e5f1ba6d-ed12-4b6a-837e-ea575eb70d7d
* Type: text
* Required: false
    */
                readonly name: Elements.TextElement;

/*
    * Bio
    *
    * Codename: bio
* Id: 426bf3b7-baca-5a97-aa73-22fb5d9de0d5
* External Id: 5aa814a3-c8ce-41a6-95ef-b5a9d40556c7
* Type: text
* Required: true
    */
                readonly bio: Elements.TextElement;

/*
    * Avatar image
    *
    * Codename: avatar_image
* Id: 80f1b2de-f65e-548b-8085-569428169577
* External Id: 0392ac27-2225-4328-b761-0eb77da154a2
* Type: asset
* Required: true
    */
                readonly avatar_image: Elements.AssetsElement;

/*
    * Email
    *
    * Codename: email
* Id: 91cf5153-9a79-5407-9ec2-a84ae8dc6555
* External Id: aefcd006-ab0a-4fe1-82e6-8c35f13035f8
* Type: text
* Required: false
    */
                readonly email: Elements.TextElement;

/*
    * Telegram
    *
    * Codename: telegram
* Id: 316b07ad-e2d7-527d-9baf-262c62e6b5ef
* External Id: 8c9712b3-537c-439b-8150-e4cbaf7fafa4
* Type: text
* Required: false
    */
                readonly telegram: Elements.TextElement;

/*
    * Twitter
    *
    * Codename: twitter
* Id: 39e61787-ca53-5471-9cd5-8fafbef0fcfd
* External Id: fd503842-5c70-4e25-ae7b-93de943b5031
* Type: text
* Required: false
    */
                readonly twitter: Elements.TextElement;

/*
    * Github
    *
    * Codename: github
* Id: fa2c33db-ce99-5f4e-8d94-d0089c6cfc00
* External Id: 02571f3a-63ea-4b9b-b0ec-54916e2b6d64
* Type: text
* Required: false
    */
                readonly github: Elements.TextElement;

/*
    * RSS
    *
    * Codename: rss
* Id: f4edf560-f081-5c89-a8f5-96dc85b739ea
* External Id: 09bbb4fa-aa20-474c-9a9e-52e947faa843
* Type: text
* Required: false
    */
                readonly rss: Elements.TextElement;

/*
    * VK
    *
    * Codename: vk
* Id: 2396e8cc-d22d-5017-9d61-1c6b23e912c0
* External Id: d34b6290-0842-4c7f-9ca8-e3f6aac53c7c
* Type: text
* Required: false
    */
                readonly vk: Elements.TextElement;}, 
AuthorTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Author
*/
export type AuthorTypeElementCodenames = 'name' | 'bio' | 'avatar_image' | 'email' | 'telegram' | 'twitter' | 'github' | 'rss' | 'vk';;

/*
    * Type guard for Author
    *
    * Id: ef0e5861-907e-5592-b4b4-cb8574a4e887
* Codename: author
* External Id: 337a4509-0793-4dda-ba6a-a071ff7e65f1
    */
export function isAuthorType(item: IContentItem | undefined | null): item is AuthorType {
                return item?.system.type === ('author' satisfies AuthorTypeCodename);
            };



            