/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Category' type
*/
            export type CategoryTypeCodename = keyof Pick<Record<TypeCodenames, null>, "category">;

            /*
* Typeguard for codename of 'Category' type
*/
            export function isCategoryTypeCodename(value: string | undefined | null): value is CategoryTypeCodename {
                return typeof value === 'string' && value === ('category' satisfies CategoryTypeCodename);
            }

/*
    * Category
    *
    * Id: 6bc05c55-cc58-52a5-8742-a48db5fcc1e2
* Codename: category
* External Id: efb4a184-1c32-4ede-bdd1-90fab6b7a7b9
    */
export type CategoryType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 9ddcb895-589f-5cbe-97a9-ef9885cb4387
* External Id: 07f584b8-db9a-4288-94a2-902af84e5190
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Slug
    *
    * Codename: slug
* Id: 1d0f8514-39a7-5f9a-8f2d-f4b1c37d54f1
* External Id: 0e300cca-86cf-4fde-adb8-e9596dd4e954
* Type: url_slug
* Required: true
    */
                readonly slug: Elements.UrlSlugElement;}, 
CategoryTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Category
*/
export type CategoryTypeElementCodenames = 'title' | 'slug';;

/*
    * Type guard for Category
    *
    * Id: 6bc05c55-cc58-52a5-8742-a48db5fcc1e2
* Codename: category
* External Id: efb4a184-1c32-4ede-bdd1-90fab6b7a7b9
    */
export function isCategoryType(item: IContentItem | undefined | null): item is CategoryType {
                return item?.system.type === ('category' satisfies CategoryTypeCodename);
            };



            