/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { MenuItemType } from '../types/menu-item-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Menu' type
*/
            export type MenuTypeCodename = keyof Pick<Record<TypeCodenames, null>, "menu">;

            /*
* Typeguard for codename of 'Menu' type
*/
            export function isMenuTypeCodename(value: string | undefined | null): value is MenuTypeCodename {
                return typeof value === 'string' && value === ('menu' satisfies MenuTypeCodename);
            }

/*
    * Menu
    *
    * Id: 4aac3f22-7a52-5f24-bca3-e36e3a539f12
* Codename: menu
* External Id: 09e9b2ba-822e-4c29-914b-970d8bc06333
    */
export type MenuType = IContentItem<
{
/*
    * Menu items
    *
    * Codename: menu_items
* Id: 7d3359e2-8520-5a54-8b89-8fd226297665
* External Id: 625a9755-d509-4855-8879-3d24f36e28e3
* Type: modular_content
* Required: false
* Allowed content types: menu_item
    */
                readonly menu_items: Elements.LinkedItemsElement<MenuItemType>;}, 
MenuTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Menu
*/
export type MenuTypeElementCodenames = 'menu_items';;

/*
    * Type guard for Menu
    *
    * Id: 4aac3f22-7a52-5f24-bca3-e36e3a539f12
* Codename: menu
* External Id: 09e9b2ba-822e-4c29-914b-970d8bc06333
    */
export function isMenuType(item: IContentItem | undefined | null): item is MenuType {
                return item?.system.type === ('menu' satisfies MenuTypeCodename);
            };



            