/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Note' type
*/
            export type NoteTypeCodename = keyof Pick<Record<TypeCodenames, null>, "note">;

            /*
* Typeguard for codename of 'Note' type
*/
            export function isNoteTypeCodename(value: string | undefined | null): value is NoteTypeCodename {
                return typeof value === 'string' && value === ('note' satisfies NoteTypeCodename);
            }

/*
    * Note
    *
    * Id: 16b7fbc7-d1cb-5969-b37b-9f0bc8b6b4c7
* Codename: note
* External Id: 2648f394-de30-4ba1-a5e6-356857f8f382
    */
export type NoteType = IContentItem<
{
/*
    * Text
    *
    * Codename: text
* Id: 650d1909-95ca-5c9f-bb06-6354c5dddff0
* External Id: 976cb91d-b824-4ff5-b8d8-f66cccdb07c6
* Type: text
* Required: false
    */
                readonly text: Elements.TextElement;}, 
NoteTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Note
*/
export type NoteTypeElementCodenames = 'text';;

/*
    * Type guard for Note
    *
    * Id: 16b7fbc7-d1cb-5969-b37b-9f0bc8b6b4c7
* Codename: note
* External Id: 2648f394-de30-4ba1-a5e6-356857f8f382
    */
export function isNoteType(item: IContentItem | undefined | null): item is NoteType {
                return item?.system.type === ('note' satisfies NoteTypeCodename);
            };



            