/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Page' type
*/
            export type PageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "page_52b1c1a">;

            /*
* Typeguard for codename of 'Page' type
*/
            export function isPageTypeCodename(value: string | undefined | null): value is PageTypeCodename {
                return typeof value === 'string' && value === ('page_52b1c1a' satisfies PageTypeCodename);
            }

/*
    * Page
    *
    * Id: 52b1c1a1-913e-4638-a24d-eacd1f5e46c3
* Codename: page_52b1c1a
    */
export type PageType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 593d40d4-8167-4caf-800f-250f59e70d9d
* Type: text
* Required: false
    */
                readonly title: Elements.TextElement;

/*
    * URL
    *
    * Codename: url
* Id: 59ff9a77-3da0-4853-978c-5bd438a926ff
* Type: url_slug
* Required: false
    */
                readonly url: Elements.UrlSlugElement;

/*
    * Show in navigation
    *
    * Codename: show_in_navigation
* Id: dcb081f3-c0af-4bb7-89aa-76b6597e939a
* Type: multiple_choice
* Required: false
    */
                readonly show_in_navigation: Elements.MultipleChoiceElement<PageTypeShowInNavigationMultipleChoiceOptions>;

/*
    * Subpages
    *
    * Codename: subpages
* Id: f3612659-c39e-4824-a640-3f7751998d48
* Type: subpages
* Required: false
    */
                readonly subpages: Elements.LinkedItemsElement<CoreType>;

/*
    * Content
    *
    * Codename: content
* Id: f9683864-f2fb-4e40-a7ec-8033f15ba874
* Type: modular_content
* Required: false
    */
                readonly content: Elements.LinkedItemsElement<CoreType>;}, 
PageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Page
*/
export type PageTypeElementCodenames = 'title' | 'url' | 'show_in_navigation' | 'subpages' | 'content';;

/*
    * Type guard for Page
    *
    * Id: 52b1c1a1-913e-4638-a24d-eacd1f5e46c3
* Codename: page_52b1c1a
    */
export function isPageType(item: IContentItem | undefined | null): item is PageType {
                return item?.system.type === ('page_52b1c1a' satisfies PageTypeCodename);
            };

export type PageTypeShowInNavigationMultipleChoiceOptions = 'yes' | 'no'

            