/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { PageType } from '../types/page-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Web spotlight root' type
*/
            export type WebSpotlightRootTypeCodename = keyof Pick<Record<TypeCodenames, null>, "web_spotlight_root">;

            /*
* Typeguard for codename of 'Web spotlight root' type
*/
            export function isWebSpotlightRootTypeCodename(value: string | undefined | null): value is WebSpotlightRootTypeCodename {
                return typeof value === 'string' && value === ('web_spotlight_root' satisfies WebSpotlightRootTypeCodename);
            }

/*
    * Web spotlight root
    *
    * Id: b100fe38-d85d-404d-95ff-15f0062f14a4
* Codename: web_spotlight_root
    */
export type WebSpotlightRootType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: 5e458527-d4b9-408f-b71e-3559e4292016
* Type: text
* Required: false
    */
                readonly title: Elements.TextElement;

/*
    * Subpages
    *
    * Codename: subpages
* Id: e4323a44-5a3a-43c6-998b-0a794ddd5f9f
* Type: subpages
* Required: false
* Allowed content types: page_52b1c1a
    */
                readonly subpages: Elements.LinkedItemsElement<PageType>;

/*
    * Content
    *
    * Codename: content
* Id: 0f9233a8-0454-4a39-82b0-5d1f619b3355
* Type: modular_content
* Required: false
    */
                readonly content: Elements.LinkedItemsElement<CoreType>;}, 
WebSpotlightRootTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Web spotlight root
*/
export type WebSpotlightRootTypeElementCodenames = 'title' | 'subpages' | 'content';;

/*
    * Type guard for Web spotlight root
    *
    * Id: b100fe38-d85d-404d-95ff-15f0062f14a4
* Codename: web_spotlight_root
    */
export function isWebSpotlightRootType(item: IContentItem | undefined | null): item is WebSpotlightRootType {
                return item?.system.type === ('web_spotlight_root' satisfies WebSpotlightRootTypeCodename);
            };



            