/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts"

/*
 * Type representing codename of 'Default' collection
 */
export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">

/*
 * Typeguard for codename of 'Default' collection
 */
export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
	return typeof value === "string" && value === ("default" satisfies DefaultCollectionCodename)
}
