/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: 🛡️ a.s.r. - Nuxt.js
 * Environment: Production
 * Id: cf6d175e-7a5d-0112-9460-c4bba590ad75
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts"

/*
 * Type representing codename of 'Czech' language
 */
export type CzechLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "cs-CZ">

/*
 * Typeguard for codename of 'Czech' language
 */
export function isCzechLanguageCodename(value: string | undefined | null): value is CzechLanguageCodename {
	return typeof value === "string" && value === ("cs-CZ" satisfies CzechLanguageCodename)
}
