import type { IContentItem } from '~/types/kontent';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 * Updated for SDK v11
 */
export type Article = IContentItem<{
  slug: any;
  date: any;
  tags: any;
  content: any;
  category: any;
  description: any;
  title: any;
}>;
