import type { IContentItem } from '~/types/kontent';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Author = IContentItem<{
  vk: any;
  telegram: any;
  twitter: any;
  bio: any;
  name: any;
  avatar_image: any;
  email: any;
  rss: any;
  github: any;
}>;
