import { IContentItem } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type MenuItem = IContentItem<{
  content: any;
  slug: any;
  label: any;
}>;
