import type { IContentItem } from '~/types/kontent';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type MenuItem = IContentItem<{
  content: any;
  slug: any;
  label: any;
}>;
