import type { IContentItem } from '~/types/kontent';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type Page = IContentItem<{
  description: any;
  meta_description: any;
  title: any;
  gatsby_template: any;
}>;
