import type { IContentItem } from '~/types/kontent';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-7'
 */
export type SiteMetadata = IContentItem<{
  title: any;
  domain: any;
  subtitle: any;
  page_not_found_message: any;
  copyright: any;
}>;
